---
title: Data assimilation and estimation theory
output:
  html_document:
    css: ./styles/base.css
    highlight: null
    theme: null
    includes:
      in_header: ./styles/notebook.html
---

STAT 775 <br>
Instructor: Colin Grudzien<br>


## Class Information:

### Class times: Fall 2021  -- MonWedFri 10:00 PM - 10:50 AM
### Class room: PE 105
### Final exam: 5:00 PM Friday December 10th, see [final exam policy](#final_exam_policy)

## Instructor information:

<table class="minimalistBlack">
<thead>
<tr>
  <th>Contact</th>
  <th>Office</th>    
  <th>Office Hours</th>
</tr>
</thead>
<tr>
  <td>CGrudzien@unr.edu</td>
  <td>DMSC 218 </td>
  <td>MonWed 4:00 - 5:30 PM on zoom</td>
</tr>
<tr>
  <td>(775) 784-7554</td>
  <td> </td>
  <td> or by appointment</td>
</tr>
</table>

## Vaccination
<p>Anyone 12 and older is eligible to receive the Pfizer COVID-19 vaccine, and anyone 18 and older is eligible to receive the Moderna or Johnson & Johnson vaccine. There are multiple locations in the community offering free vaccination. Vaccinations and testing are also available for free at the <a href="/coronavirus/testing">Student Health Center</a> for students, faculty and staff.</p>

### Vaccination sites
  
  * <a href="https://www.covid19washoevaccine.com/pages/find-vaccine">List of vaccination sites in Washoe County</a>
  * <a href="https://www.washoecounty.us/health/">Washoe County Health Department clinics</a>
  * <a href="https://www.immunizenevada.org/covid-19-vaccine-locator">Immunize Nevada list of clinics</a>

## Communication

Announcements and course updates will be posted in <a href="https://unr.canvaslms.com/login/canvas" target="blank">Webcampus</a>.  Students are expected to keep up-to-date on the course by reading these announcements for important information on assignments, midterms, etc.




### Help & Questions

There will be a classroom discussion forum where you can seek help from the instructor and peers about the assignments.  Some assignments will require that you post and discuss results in this forum.

The best way to contact the instructor is via email or message within Webcampus.  Messages received before 4:00 PM during business days will usually get a response the same day.  Emails received after 4:00 PM or during the weekend are not guaranteed a same-day response.  Longer questions will not be answered by email and will be directed to appointments or office hours.

The instructor will be __available from 4:00 - 5:30 PM MonWed for public office hours and questions, shared with students from STAT 445 / 645__.  If you cannot attend office hours or if you need to discuss something privately you can set an appointment with the instructor directly. 

### Netiquette

When communicating online, you should always:

 * Treat your instructor and peers with respect, even in email or in any other online communication.

 * Use clear and concise language.  Be respective of readers’ time and attention.

 * Remember that all college level communication should have correct spelling and grammar.

 * Avoid slang terms and texting abbreviations.

 * Use standard fonts that are optimized for online reading (e.g., sans serif) along with a consistent and readable size (12 or 14 pt.)

 * Avoid using the caps lock feature AS IT CAN BE INTERPRETED AS YELLING.

 * Limit and possibly avoid the use of emoticons.  Not everyone knows how to interpret them.

 * Be cautious when using humor or sarcasm as tone is sometimes lost in an email or discussion post and your message might be taken literally or offensively.

 * Be careful sharing personal information online (both yours and other’s).

 * Always give proper credit when referencing or quoting another source. (Corollary:  Don’t copy and paste another student’s post and claim it as original as that is essentially plagiarism.)

 * Don’t repeat someone else’s post without adding something of your own to it. (See corollary above regarding reuse of someone else’s post.)

 * Always be respectful of others’ opinions even when they differ from your own. When you disagree with someone, you should express your differing opinion in a respectful, non-critical way. (Corollary:  Do not make personal or insulting remarks.)

## Course description

### Content

Data assimilation (DA) refers to techniques used to combine the data from physics-based, numerical models and real-world observations to produce an estimate for the state of a time-evolving random process and the parameters that govern its evolution. Owing to their history in numerical weather prediction, DA systems are designed to operate in an extremely large dimension of model variables and observations, often with sequential-in-time observational data. As a long-studied “big-data” problem, DA has benefited from the fusion of a variety of techniques, including methods from Bayesian inference, dynamical systems, numerical analysis, optimization, control theory and machine learning.  DA techniques are widely used in many areas of geosciences, neurosciences, biology, autonomous vehicle guidance and various engineering applications requiring dynamic state estimation and control.  

After introducing students to essential elements of linear estimation theory, this course will focus on the development and application of operational, statistical learning algorithms in nonlinear, physics-based models. The course will rely on the Python programming language for many exercises and for the final project, with the DAPPER library providing a framework for the class. The DAPPER library is suitable for small- to mid-scale DA and uncertainty quantification research and provides a pedagogical stepping stone for students to high-performance libraries and / or writing their own solvers.  Students do not need to know Python programming in advance, but some familiarity with programming and computation generally will be beneficial.  [final exam policy](#final_exam_policy).

### Structure for online learning

This class will follow a flipped design in which students are expected to watch one or more short lectures before the class session.  __If a student is unable to or would prefer not to attend in person, a hy-flex remote learning option will be granted.__  Video lectures will cover content that is relevant to the day's activity in class.  Class sessions will be held on Zoom and students are expected to attend the Zoom meeting to work on the day's activities with their cohort.  Students should have a laptop for working through activities during class in-person class in the Python programming language, or should be able to attend remotely with a computer that will accommodate this.  The day's activities will require posting a discussion of the results according to the assignment rubric in the forum for completion credit.  Programming experience in Python is not required and there will be bi-weekly assignments in DataCamp that will build on fundamental skills in the Python scientific programming environment. 


## Prerequisites

This is an applied course with some treatment of essential theoretical foundations.   This course is targeted at statistics and applied mathematics PhD and Masters students, but is open to motivated non- mathematics / statistics majors and undergraduates.  The minimum background needed is the following, though students will benefit from the recommended background.  Exceptions may be made on a case-by-case basis.  Please contact the instructor for approval for enrollment

* MATH 283 (Multivariate calculus) or equivalent,
* MATH 330 (Linear algebra) or equivalent,
* STAT 352 (Probability and Statistics) or equivalent.
* Basic familiarity with programming and computation.

### Recommended background:
This course will treat some of the topics in the following courses.  Students will benefit from taking these courses in advance, or concurrently, but these courses are not strictly required.

* MATH 285 (Differential equations) or equivalent
* STAT 461/462 (Probability and Stochastic Processes) or equivalent
* STAT 445 (Introduction to Statistical Computing) or equivalent
* STAT 446  (Introduction to Bayesian Statistics) or equivalent


## Required software and technology
By signing up for this class you acknowledge the responsibility to have access to:
<ul>
 <li> A desktop or a laptop computer <strong>supporting Python 3.8 or higher, that you can install statistical software on, download data to and attend Zoom discussions.</strong>.</li>
 <li> If attending hy-flex, a reliable internet connection to consistently attend class activities and to access online class content or examination.</li>
</ul>

In the first two weeks of class students are required to obtain a free educational license of [DataCamp](https://www.datacamp.com/), with instructions sent in an announcement by the instructor.  <strong>You do not have to pay for DataCamp so please await instructions on how to sign up free through STAT 775.</strong>

You will also need to install the following software for class assignments:
        <ul>
            <li>Python 3.8 or higher is required for the class.  Students are strongly encouraged to use <a href="https://www.anaconda.com/products/individual">Anaconda</a> or a <a href="https://docs.conda.io/en/latest/miniconda.html">MiniConda installer</a> to manage Python packages and other dependencies.</li>
            <li> The course will utilize the [DAPPER library](https://github.com/nansencenter/DAPPER) which will need to be cloned from the Github.</li>
            <li>Students are also required to install <a href='https://www.latex-project.org/' target='blank'>LaTeX (free typesetting language)</a>.  This is required to compile Markdown,
            and is the standard for writing mathematical and statistical reports and publications.</li>
            <li>Advanced students interested in the theory of programming are recommended <a href='https://eloquentjavascript.net/' target='blank'>Eloquent Javascript (free, creative commons)</a>.</li>
        </ul> 

## Required book
There is no required textbook for this class.  Students will be expected to follow the video lectures and the class activities to learn the content of this course, but additional	recommended resources are the following:
<ul>
  <li>J.L. Speyer and W.H. Chung. <i>Stochastic processes, estimation, and control</i>. Vol. 17. SIAM, 2008.</il>
  <li>M. Asch, M. Bocquet, and M. Nodet. <i>Data assimilation: methods, algorithms, and applications</i>. Vol. 11. SIAM, 2016.</li>
</ul> 

The course will __loosely__ follow Chapters 1 - 5 and 7 from <i>Stochastic processes, estimation, and control</i> and Chapters 1 - 3 and 6 - 11 of <i>Data assimilation: methods, algorithms, and applications</i>.  Other sources of material will include relevant journal articles and surveys. 


## Electronic resources

### [Web Campus](https://wcl.unr.edu)

Students are responsible for checking  their email accounts and Web Campus for announcements.  Students are assumed to be aware of all information posted to these sources prior to each meeting.  __Announcements, homework and grades will be posted in Web Campus.__


	 	
### [Course archive page](https://cgrudz.github.io/teaching/stat_775_2021_fall/)
	
This page includes an archive of lecture notes and activities from the class, along with the current schedule for the semester.


## Student learning outcomes
Students will learn:

  * Essential elements of estimation theory and a survey of modern applications and challenges.
  * How to develop and analyze algorithms for nonlinear filtering and smoothing.
  * How to implement, and to present reproducible benchmarks of, estimation algorithms on nonlinear models.



## Assignments and grading

### Video lectures
Each week there will usually be three video lectures to watch before the class activities during the normal class sessions.

### Activities
In a normal class session, students will work through a class activity that uses the content from the video lectures that week.  The activity will require a written summary and analysis at the end of the day according to the activity rubric.  

### Homework
 The following DataCamp courses will be required for completion credit in the fall:

  * Introduction to Python 
  * Intermediate Python 
  * Importing data in Python 
  * Python Data Science Toolbox Part 1 
  * Python Data Science Toolbox Part 2 
  * Data Types for Data Science in Python 
  * Writing Efficient Python Code 
  * Writing functions in Python 



### <a id="final_exam_policy"></a> Final exam policy

The final exam will consist of a final term report written on one of several available topics to choose from in the assignment.  The __final project must be submitted on WebCampus by 5:00 PM on Friday, December 10th__.  Details on the assignment are in the <a href="./final_exam.html" target="blank">final project description</a>.


## Final grades

Final grades will be calculated according to the following:  <br>

<table class="minimalistBlack">
<thead>
<tr>
  <th>Category</th>
  <th>Percent of final grade</th>
</tr>
</thead>
<tr>
  <td>Class activities</td>
  <td>$50\%$ </td>
</tr>
<tr>
  <td>DataCamp Reading Assignments</td>
  <td> $25\%$ </td>
<tr>
  <td>Term Paper</td>
  <td>$25\%$ </td>
</tr>
</table>

<br>
The final letter grade will be assigned according to the weighted score as in the following table:

<table class="minimalistBlack">
<thead>
<tr>
  <th>Weighted score $x$</th>
  <th>Final letter grade</th>
</tr> 
</thead>
<tr>
  <td>$90\% \leq x \leq 100\%$</td>    
  <td> A</td>
</tr>
<tr>
  <td>$80\% \leq x < 90\%$</td>    
  <td> B </td>
</tr>
<tr>
  <td>$70\% \leq x < 80\%$</td>
  <td> C</td>
</tr>
<tr>
  <td>$60\% \leq x < 70\%$</td>
  <td> D</td>
</tr>
<tr>
  <td>$0 \% \leq x < 60\%$</td>
  <td>F</td>
</tr>
</table>

## Important dates

Please see the [UNR Academic Calendar](https://www.unr.edu/academic-central/academic-resources/academic-calendar##Spring%202020) for important dates in the semester.

## Late policy and exceptions


There are no makeups for participation assignments, DataCamp assignments or the final term paper except for university recognized activities or exceptional circumstances, as per university policy.  To accommodate unforeseen circumstances, __the lowest DataCamp score and the lowest two participation scores will be dropped from the final grade calculation__.  If a student needs to miss class due to participation in official university activities or a religious observance, they __must make arrangements with the instructor at least one week prior to the date in question -- the absence will not be given consideration without this advanced notice__.   In cases of absences due to extended illness, family emergency, bereavement, or other compelling reason, students should notify the instructor as soon as possible and __within one week of the start of the absence__.  The instructor has the right to request formal, written documentation in such cases as they deem appropriate.  Please see the [full policy statement on absences](https://www.unr.edu/administrative-manual/3000-3999-students/3020-class-absence-policy).


## Diversity statement

The University of Nevada, Reno is committed to providing a safe learning and work environment for all. Students are expected to treat each other and the instructor with respect.  No form of harassment, discrimination or bullying will be tolerated.  If
you believe you have experienced discrimination, sexual harassment, sexual assault, domestic/dating violence,
or stalking, whether on or off campus, or need information related to immigration concerns, please contact the
University's Equal Opportunity & Title IX Office at (775) 784-1547. Resources and interim measures are available
to assist you. For more information, please visit the [Title IX website for UNR](https://www.unr.edu/equal-opportunity-title-ix)


## Disability services

Any student with a disability needing academic adjustments or accommodations is requested to speak with the Disability Resource Center (Pennington Student Achievement Center, Suite 230) as soon as possible to arrange for appropriate accommodations.  More information can be found at the [DRC website](https://www.unr.edu/drc).


## Academic conduct


No laptops, cell phones, mp3 players, or other electronics are to be used for personal reasons in class. If you
are being disruptive during class you will be asked to leave. Disruptions in this context include inadequate
participation. Please see our official [Student Code of Conduct](https://www.unr.edu/student-conduct).


## Academic success services


A common habit among successful students is to seek help outside of the classroom. Your student fees cover
use of the [Math Center](https://www.unr.edu/mathcenter) (784-4433), [Tutoring Center](https://www.
unr.edu/tutoring-center) (784-6801), and [University Writing Center](https://www.unr.edu/writing-center) (784-6030).
These centers support your classroom learning; it is your responsibility to take advantage of their services.


## Statement on Audio and Video Recording

Zoom meetings will generally be recorded and you will be asked for consent to be recorded to participate in these meetings.  Surreptitious or covert video-taping of class or unauthorized audio recording of class is prohibited by law and by Board of Regents policy. This class may be videotaped or audio recorded only with the written permission of the instructor. In order to accommodate students with disabilities, some students may be given permission to record class lectures and discussions. Therefore, students should understand that their comments during class may be recorded.


## Academic dishonesty

Cheating, plagiarism, or otherwise obtaining grades under false pretenses constitutes academic dishonesty according to the code of this university. Academic dishonesty will not be tolerated and penalties can include canceling a
students enrollment without a grade or giving an F for the assignment or for the entire course. For more details, see the University of Nevada, Reno general catalog.  The University Academic Standards Policy defines academic dishonesty, and mandates specific sanctions for violations. See the [University Academic Standards policy: UAM 6,502](https://www.unr.edu/administrative-manual/6000-6999-curricula-teaching-research/instruction-research-procedures/6502-academic-standards).

</div>
