# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Colin Grudzien'
tagline:          'A home page'
description:      '&nbsp;&ensp;&emsp;&emsp;&emsp;Amid high minds<br>and low lives.'
url:              https://cgrudz.github.io/ 
baseurl:          /

author:
  name:           'Colin Grudzien'
  url:            https://github.com/cgrudz

# Gems
gems: [jekyll-paginate,jekyll-gist,pygments]
paginate:         5
paginate_path: "page:num"

