# Activity 09/20/2021

## STAT 445 / 645 -- Section 1001 <br> Instructor: Colin Grudzien<br>

## Instructions:
We will work through the following series of activities as a group.

## Activities:

### Activity 2: Binomial trials

#### Exercise 1:

Suppose that an urn contains 4 red marbles and 6 blue marbles.  Suppose that we consider a trial successful when we draw a blue marble from the urn and we proceed to take 8 draws from the urn with replacement.

What is the probability of selecting 3 or more blue marbles in the 8 draws?  Can you compute this in two ways using both the probability mass function and the CDF?


#### Exercise 2:

Can you plot the full probability distribution for the last experiment?  Try to include appropriate labels for this plot in the axes and in the title.


#### Exercise 3:
Can you perform the same but instead for the cumulative distribution?


### Activity 3: Poisson trials

#### Exercise 1:

Suppose that we are modeling the number of calls that arrive in an hour at a call center.  Suppose that the number of calls in one hour is independent from any other hour and the mean number of any calls in an hour is constant, equal to 15.

What is the probability of receiving 10 or less calls in a given hour?


#### Exercise 2:

Can you plot the probability distribution for the last experiment, up to 50 possible calls?  Try to include appropriate labels for this plot in the axes and in the title.


#### Exercise 3:
Can you perform the same but instead for the cumulative distribution?

#### Exercise 4:

If we want to use the Poisson distribution as above to model the distribution of the calls in an hour, what should the standard deviation be in the number of calls received in an hour?
